name: Continuous Deployment - Base

on:
  push:
    branches:
      - main
    paths:
      - base/**
      - .github/workflows/base-deployment.yml

jobs:
  Base-Image-Dockerhub:
    name: Publish Base image to Dockerhub
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: favware/codespaces-containers
          workdir: base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest,base,main'
