name: Continuous Deployment - With Node Canvas

on:
  push:
    branches:
      - main
    paths:
      - with-node-canvas/**
      - .github/workflows/canvas-deployment.yml

jobs:
  Canvas-Image-Publish:
    name: Publish image to container registries
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1.6.0
      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # renovate: tag=v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # renovate: tag=v2.7.0
        with:
          push: true
          context: ./with-node-canvas
          tags: |
            favware/codespaces-containers:with-node-canvas
            favware/codespaces-containers:with-canvas
            favware/codespaces-containers:canvas
            ghcr.io/favware/codespaces-containers:with-node-canvas
            ghcr.io/favware/codespaces-containers:with-canvas
            ghcr.io/favware/codespaces-containers:canvas
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2.4.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: favware/codespaces-containers
          short-description: Favware-provided GitHub Codespaces Containers image with node-canvas